export const TRANSACTION_AWARE_DATA_SOURCE = Symbol('TRANSACTION_AWARE_DATA_SOURCE');
export const EXECUTION_LOG_STORE = Symbol('EXECUTION_LOG_STORE');
export const OUTBOX_STORE = Symbol('OUTBOX_STORE');
export const USE_CASE_EXECUTION_STORE = Symbol('USE_CASE_EXECUTION_STORE');
export const EXECUTION_LEASE_OWNER_ID = Symbol('EXECUTION_LEASE_OWNER_ID');
export const DOCUMENTS_RUNNER = Symbol('DOCUMENTS_RUNNER');
export const DOCUMENTS_READER = Symbol('DOCUMENTS_READER');
export const DOCUMENTS_USE_CASE_EXECUTOR = Symbol('DOCUMENTS_USE_CASE_EXECUTOR');
